# -*- coding: utf-8 -*-
"""Text_to_Image_generation_using_DALL-E_Mini(Project_2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gkg8N2iga9iW0SDkjYQdnZ3l8ntZkm6s

# Install Required Libraries
"""

!pip install min-dalle -q

from min_dalle import MinDalle
model = MinDalle(is_mega=True, is_reusable=True)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# text = "A car"
# seed = 6
# grid_size = 2
# 
# display(model.generate_image(text, seed, grid_size))

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# text = "Burj khalifa"
# seed = 6
# grid_size = 2
# 
# display(model.generate_image(text, seed, grid_size))

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# text = "A tiger wearing sunglass"
# seed = 6
# grid_size = 2
# 
# display(model.generate_image(text, seed, grid_size))

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# text = "A cat wearing a hat"
# seed = 6
# grid_size = 2
# 
# display(model.generate_image(text, seed, grid_size))

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# text = "A godzilla bitting mecha godzilla"
# seed = 6
# grid_size = 2
# 
# display(model.generate_image(text, seed, grid_size))

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# text = "A boy eating chocolate"
# seed = 6
# grid_size = 2
# 
# display(model.generate_image(text, seed, grid_size))

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# text = "A mobile phone"
# seed = 6
# grid_size = 2
# 
# display(model.generate_image(text, seed, grid_size))

